version: '3.1'

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: lpbrochu/dask
    hostname: dask-scheduler
    environment:
      - affinity:node==ohyk4294ekklee3z9wlvfi8ow
    ports:
      - "18786:8786"
      - "18787:8787"
    command: ["dask-scheduler"]
    volumes:
      - ~/workspace:/home/jovyan/workspace

  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: lpbrochu/dask
    hostname: dask-worker
    command: ["dask-worker 192.168.2.32:18786"]
    volumes:
      - ~/workspace:/home/jovyan/workspace
    deploy:
      mode: replicated
      replicas: 2

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: lpbrochu/dask-notebook
    hostname: notebook
    ports:
      - "18888:8888"
    volumes:
      - ~/workspace:/home/jovyan/workspace
