version: '3.1'

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: 192.168.43.229:5000/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    volumes:
      - ~/workspace:/home/jovyan/workspace

  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: 192.168.43.229:5000/dask
    hostname: dask-worker
    command: ["dask-worker 192.168.43.229:8786"]
    volumes:
      - ~/workspace:/home/jovyan/workspace

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: 192.168.43.229:5000/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    volumes:
      - ~/workspace:/home/jovyan/workspace
